version: 2
jobs:
  build:
    machine:
      post:
    - FILE=$CIRCLE_ARTIFACTS/memory-usage-actual.txt; while true; do ps -u ubuntu eo pid,%cpu,%mem,args,uname --sort=-%mem >> $FILE; echo "----------" >> $FILE; sleep 1; done:
          background: true
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      _JAVA_OPTIONS: "-Xms512m -Xmx2048m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"
    steps:
    - checkout
    - run:
        name: Accept licenses
        command: |
          mkdir -p "$ANDROID_HOME/licenses"
          echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
          echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_HOME/licenses/android-sdk-license"
          echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
          sdkmanager --licenses
    - run:
        name: Setup emulator
        command: sdkmanager --install "system-images;android-22;default;armeabi-v7a"
    - run:
        name: Create emulator
        command: |
          cd $ANDROID_HOME/tools/bin
          echo "no" | ./avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
    - run:
        name: Launch emulator
        command: |
          cd $ANDROID_HOME/emulator
          export LD_LIBRARY_PATH=$ANDROID_HOME/emulator/lib64:$ANDROID_HOME/emulator/lib64/qt/lib
          ./emulator -avd test -noaudio -no-boot-anim -no-window -accel on
          circle-android wait-for-boot
          sleep 30
          adb shell input keyevent 82
        background: true
        parallel: true
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - run:
        name: Run all checks
        command: ./gradlew check
    - run:
        name: Run UI Tests
        command: ./gradlew connectedCheck
    - store_artifacts:
        path: library/build/reports
        destination: reports
    - store_test_results:
        path: library/build/test-results