object Depends {
    const val testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    const val appcompat = "androidx.appcompat:appcompat:${Versions.androidXLib}"
    const val coreKtx = "androidx.core:core-ktx:${Versions.androidXCoreKtx}"
    const val recycler = "androidx.recyclerview:recyclerview:${Versions.androidXLib}"
    const val paging = "androidx.paging:paging-runtime:${Versions.paging}"
    const val pagingRx = "androidx.paging:paging-rxjava2:${Versions.paging}"
    const val lifecycle = "androidx.lifecycle:lifecycle-extensions:${Versions.androidXLifecycleLib}"
    const val lifecycleCompiler = "androidx.lifecycle:lifecycle-compiler:${Versions.androidXLifecycleLib}"
    const val design = "com.google.android.material:material:${Versions.androidXMaterialLib}"
    const val picasso = "com.squareup.picasso:picasso:${Versions.picasso}"
    const val picassoDownloader = "com.jakewharton.picasso:picasso2-okhttp3-downloader:${Versions.picassoDownloader}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
    const val rxJava = "io.reactivex.rxjava2:rxjava:2.2.7"
    const val dagger = "com.google.dagger:dagger:${Versions.dagger}"
    const val daggerAndroid = "com.google.dagger:dagger-android-support:${Versions.dagger}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    const val daggerProcessor = "com.google.dagger:dagger-android-processor:${Versions.dagger}"
    const val assistedInject = "com.squareup.inject:assisted-inject-annotations-dagger2:${Versions.assistedInject}"
    const val assistedInjectProcessor =
        "com.squareup.inject:assisted-inject-processor-dagger2:${Versions.assistedInject}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofitGsonConverter = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val retrofitRxJava2Adapter = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofit}"
    const val okhttpLoggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttpLoggingInterceptor}"
    const val annotations = "androidx.annotation:annotation:1.0.0"
    const val room = "androidx.room:room-common:${Versions.room}"
    const val roomRuntime = "androidx.room:room-runtime:${Versions.room}"
    const val roomCompiler = "androidx.room:room-compiler:${Versions.room}"

    const val kotlinTest = "org.jetbrains.kotlin:kotlin-test-junit:${Versions.kotlin}"
    const val robolectric = "org.robolectric:robolectric:${Versions.robolectric}"
    const val junit = "junit:junit:${Versions.junit}"
    const val mockito = "com.nhaarman:mockito-kotlin:${Versions.mockito}"
    const val dexmaker = "com.linkedin.dexmaker:dexmaker-mockito:2.19.0"
    const val roomTesting = "androidx.room:room-testing:${Versions.room}"
    const val coreTesting = "androidx.arch.core:core-testing:${Versions.androidXArchTesting}"
    const val multidexInstrumentation = "androidx.multidex:multidex-instrumentation:2.0.0"
    const val coreCommon = "androidx.arch.core:core-common:2.0.0-rc01"
    const val coreRuntime = "androidx.arch.core:core-runtime:2.0.0-rc01"

    const val testRunner = "androidx.test:runner:${Versions.androidXTest}"
    const val testRules = "androidx.test:rules:${Versions.androidXTest}"
    const val espressoCore = "androidx.test.espresso:espresso-core:${Versions.androidXEspresso}"
    const val espressoIntents = "androidx.test.espresso:espresso-intents:${Versions.androidXEspresso}"
    const val androidAnnotations = "androidx.annotation:annotation:${Versions.androidXLib}"
}